notifications:
  email: false
dist: xenial
env:
  global:
    - ANDROID_PLATFORM_VERSION=9
    - ANDROID_API_VERSION=28
    - ANDROID_BUILD_TOOLS_VERSION=28.0.3
cache: yarn
jobs:
  include:
    - name: Unit tests
      language: node_js
      node_js: 10
    - name: E2E tests (android)
      language: android
      jdk: oraclejdk8
      before_cache:
        - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
      cache:
        yarn: true
        directories:
          - $HOME/.gradle/caches/
          - $HOME/.gradle/wrapper/
          - $HOME/.android/build-cache
      android:
        components:
          - tools
          - platform-tools
          - build-tools-$ANDROID_BUILD_TOOLS_VERSION
          - android-$ANDROID_API_VERSION
          - extra-google-google_play_services
          - extra-google-m2repository
          - extra-android-m2repository
          - addon-google_apis-google-$ANDROID_API_VERSION
          - sys-img-x86-android-$ANDROID_API_VERSION
      before_install:
        - openssl aes-256-cbc -K $encrypted_78b6aab41b54_key -iv $encrypted_78b6aab41b54_iv -in android/app/my-release-key.keystore.enc -out android/app/my-release-key.keystore -d
        - export NODE_VERSION=${TRAVIS_NODE_VERSION:=10}
        - nvm install $NODE_VERSION
        - npm install -g yarn
      install:
        - yarn install
        - yarn run build:android
      before_script:
        - echo no | android create avd -f -n $(node -p 'require("./package.json").name') -t android-$ANDROID_API_VERSION --abi x86 -c 128M # NOTE-RT: This should really be `yarn run emulator:android:create`
      script:
        - yarn run e2e
      after_script:
        - yarn run poste2e # NOTE-RT: Make sure we kill things and clean up
        - android delete avd -n $(node -p 'require("./package.json").name') # NOTE-RT: This should really be `yarn run emulator:android:delete`
